[package]
name = "hcdev-rust"
version = "0.1.0"
authors = ["philipbeadle <philip.beadle@live.com.au>"]

[dependencies]
hc_core = { git = "https://github.com/holochain/holochain-rust", branch = "develop" }
clap = "2.31.2"
